---
sudo: true
language: ruby
cache: bundler

rvm:
  - 2.5.3

# services:
#   - mysql
#   - postgresql

env:
  - DB=mysql2
  - DB=pg
  - DB=sqlite3

gemfile:
  - gemfiles/gemfile_50.gemfile
  - gemfiles/gemfile_51.gemfile
  - gemfiles/gemfile_52.gemfile
  - gemfiles/gemfile_60.gemfile

before_script:
  - [ '$DB' = 'mysql2' ] && sudo systemctl mysql start
  - [ '$DB' = 'pg' ]     && sudo /etc/init.d/postgresql start 9.3
  - [ '$DB' = 'mysql2' ] && mysql -e 'create database hash_options_test;' || true
  - [ '$DB' = 'pg' ]     && psql -c 'create database hash_options_test;' -U postgres || true
