common: &common
  database: hash_options_test
  encoding: utf8
  host: "127.0.0.1"
  pool: 3
  wait_timeout: 5
  min_messages: WARNING

sqlite3:
  <<: *common
  adapter: sqlite3
  database: ":memory:"

pg:
  <<: *common
  adapter: postgresql
  username: <%= ENV.fetch("PGUSER", "postgres") %>
  password: <%= ENV.fetch("PGPASSWORD", "postgres") %>
  schema_search_path: public

mysql2:
  << : *common
  adapter: mysql2
  port: 3306
  username: root
  password: <%= ENV.fetch("MYSQL_PWD", "password") %>
