name: run-test-suite
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - '3306:3306'
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    runs-on: ubuntu-latest
    strategy:
     # fail-fast: true
      matrix:
        include:
          - ruby: 2.7
            activerecord: 52
          - ruby: 2.7
            activerecord: 60
          - ruby: 2.7
            activerecord: 61
          - ruby: 3.0
            activerecord: 61
    env:
       PGUSER: postgres
       PGPASSWORD: postgres
       PGDATABASE: postgres
       PGHOST: 127.0.0.1
       PGPORT: 5432
       MYSQL_HOST: 127.0.0.1
       MYSQL_DB: hash_options_test
       MYSQL_USER: root
       MYSQL_ALLOW_EMPTY_PASSWORD: yes
       MYSQL_PASSWORD:
       BUNDLE_GEMFILE: gemfiles/gemfile_${{ matrix.activerecord }}.gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        # This will automatically get bug fixes and new Ruby versions (see https://github.com/ruby/setup-ruby#versioning)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup mysql test database
        run: |
          sudo /etc/init.d/mysql start
          mysql  –h 127.0.0.1 -e 'create database IF NOT EXISTS hash_options_test;' -u${{ env.MYSQL_USER }}
          echo "it won't get to this line"
      - name: Setup postgres test database
        run: |
          sudo /etc/init.d/postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
          psql -U postgres -c 'create database hash_options_test;'
      - name: Run pg tests
        env:
          DB: pg
        run: bundle exec rake
      - name: Run mysql tests
        env:
          DB: mysql2
        run: bundle exec rake
      - name: Run sqlite tests
        env:
          DB: sqlite3
        run: bundle exec rake
